import { z } from 'zod';

export const questionOptionSchema = z.object({
    text: z.string().min(1, 'Option value is required'),
    index: z.number().min(0),
});

export const questionSchema = z.object({
    // Abacus specific fields
    operations: z.array(z.number()).optional(),
    operatorType: z.enum(['addition', 'subtraction', 'multiplication', 'division', 'mixed']).optional(),
    correctAnswer: z.number().optional(),

    // Display configuration
    digits: z.number().min(1).max(5).optional(),
    rowsCount: z.number().min(2).max(20).optional(),

    // MCQ fields
    options: z.array(questionOptionSchema).min(2, 'At least 2 options are required').max(4, 'Maximum 4 options allowed'),
    correctOptionIndex: z.number().min(0).max(3),
    marks: z.number().min(1).default(1),

    // Optional legacy/metadata
    text: z.string().optional(), // Can act as a "Word Problem" text if needed
    imageUrl: z.string().optional(),
    isAutoGenerated: z.boolean().default(false),
});

export type QuestionFormValues = z.infer<typeof questionSchema>;

export const questionGenerationConfigSchema = z.object({
    count: z.number().min(1).max(100).default(10),
    digits: z.number().min(1).max(5).default(1),
    rows: z.number().min(2).max(15).default(3),
    operators: z.array(z.enum(['addition', 'subtraction', 'multiplication', 'division'])).min(1, 'Select at least one operator'),
    allowNegative: z.boolean().default(true),
});

export type QuestionGenerationConfig = z.infer<typeof questionGenerationConfigSchema>;
