export type BankType = 'competition' | 'mock_test';
export type BankStatus = 'draft' | 'published' | 'archived';
export type OperatorType = 'addition' | 'subtraction' | 'multiplication' | 'division' | 'mixed';

// Grade levels: 0 = UKG, 1-8 = Grades 1-8
export const GRADE_OPTIONS = [
    { value: 0, label: 'UKG' },
    { value: 1, label: 'Grade 1' },
    { value: 2, label: 'Grade 2' },
    { value: 3, label: 'Grade 3' },
    { value: 4, label: 'Grade 4' },
    { value: 5, label: 'Grade 5' },
    { value: 6, label: 'Grade 6' },
    { value: 7, label: 'Grade 7' },
    { value: 8, label: 'Grade 8' },
];

export const OPERATOR_OPTIONS = [
    { value: 'addition', label: 'Addition (+)' },
    { value: 'subtraction', label: 'Subtraction (−)' },
    { value: 'multiplication', label: 'Multiplication (×)' },
    { value: 'division', label: 'Division (÷)' },
    { value: 'mixed', label: 'Mixed Operations' },
];

export interface QuestionBank {
    id: string;
    title: string;
    description?: string;
    minGrade: number;
    maxGrade: number;
    tags: string[];
    isActive: boolean;
    bankType: BankType;
    status: BankStatus;
    questionsCount: number;
    usageCount: number;
    totalMarks: number;
    createdAt: Date;
    updatedAt: Date;
}

export interface QuestionOption {
    id?: string;
    text: string;
    index: number;
}

// Abacus-style question with operations
export interface Question {
    id: string;
    bankId: string;
    // For abacus: operations is the array of numbers (with signs for subtraction)
    // e.g., [15, 8, -3, 12] means 15 + 8 - 3 + 12 = 32
    operations: number[];
    operatorType: OperatorType;
    correctAnswer: number;
    // MCQ options - one correct, three wrong
    options: QuestionOption[];
    correctOptionIndex: number;
    digits: number;
    rowsCount: number;
    marks: number;
    isAutoGenerated: boolean;
    sortOrder: number;
    createdAt: Date;
    // Legacy field - used for text-based questions
    text?: string;
    imageUrl?: string;
}

export interface QuestionBankFilters {
    search?: string;
    minGrade?: number;
    maxGrade?: number;
    isActive?: boolean;
    bankType?: BankType;
    status?: BankStatus;
    page?: number;
    limit?: number;
}

// Configuration for auto-generating questions
export interface QuestionGenerationConfig {
    operators: OperatorType[];
    count: number;
    digits: number;
    rows: number; // Number of operands for addition/subtraction
}
